language: php
php:
  - 5.6
  - 5.5
  - 5.4
  - 5.3
  - hhvm
  
matrix:
  allow_failures:
    - php: 5.6
    - php: hhvm

before_script:
  - curl -sS https://getcomposer.org/installer | php
  - chmod +x ./composer.phar
  - ./composer.phar --version
  - ./composer.phar install --dev
  
notifications:
  email:
    recipients:
      - anilnpaul@gmail.com
    on_success: never
    on_failure: always